server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
            defaultZone: http://eurekaserver:8761/eureka
  instance:
    hostname: eurekaserver
    prefer-ip-address: true
