spring:
  application:
    name: "gateway"

server:
  port: 8080
  eureka:
    client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka
    instance:
      hostname: gateway
      preferIpAddress: true
